# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "W. Andrew Barr"
description: > # this means to ignore newlines until "email:"
   paleoecology, human evolution, academic computing

email: wabarr@gmail.com
#blog logo
logo: "/assets/images/author.jpg"
# blog cover
cover: "/assets/images/mlpcamp.jpg"

name: 'W. Andrew Barr'
author: 'W. Andrew Barr'
author_image: "/assets/images/author.jpg"

permalink: /ancienteco/:categories/:year/:month/:day/:title.html

paginate: 15
paginate_path: "/ancienteco/page:num"

url: "http://wabarr.com" # the base hostname & protocol for your site
#baseurl: "/personal"

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wabarree
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/physanthphylogeny
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/wabarr
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

#allows redirects
gems:
  - jekyll-redirect-from